baseURL: https://example.com
languageCode: ro
defaultContentLanguage: ro
title: Adi's Blog
theme: cupper-hugo-theme
#googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
#enableGitInfo: true

taxonomies:
  tag: tags

imaging:
  quality: 99

params:
  description: My personal website (+ blog)
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  navTitleText: Adrian Alexiu
  # navLogo: images/me.jpeg
  logoAlt: An alternative text description of the logo
  # customCss:
  #   - css/custom_01.css
  #   - css/custom_02.css
  # customJs:
  #   - js/custom_01.js
  #   - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    # - name: Tags
    #   url: /tags/
    #   weight: 3
    - name: About
      url: /about/
      weight: 4
    # - name: RSS
    #   url: /index.xml
    #   weight: 5